steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/<your-project-id>/firstname-studentid:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/<your-project-id>/firstname-studentid:$COMMIT_SHA']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
